### ISSUE TITLE
something might be wrong with the 3.0.0-alpha.2 compiled/minified file?

### ISSUE THREAD

**Issue by FotisK** [akfish/node-vibrant#87] opened 2019-02-12 13:08 UTC
I downloaded the 3.0.0-alpha.2 from the releases directory and tried calling the minified js by using `<script src="./js/vibrant.min.js"></script>` inside a static HTML page.
and merely calling the js displays on the console the following javascript error (macOS/Safari 12):

> left hand side of operator '=' must be a reference

When using the debug version & map file, the error log is empty.
I'm a js newbie, so not sure what the issue might be, but I thought of reporting it!

**Comment by crutchcorn** [comment] 2019-06-04 05:11
Tested, confirmed fixed in a new version (under version 3.1, no breaking changes since 3.x). Please let me know if this still isn't working for some reason. Sorry about that!

**Closed** 2019-06-04 05:12 UTC
Labels: bug
