### ISSUE TITLE
Bug: Renders canvas elements visible on the page

### ISSUE THREAD

**Issue by danpalmer** [akfish/node-vibrant#36] opened 2017-02-22 14:16 UTC
While we could solve this with the addition of some CSS, it's a little tricky to target the canvas elements created by node-vibrant as they have no class and are not contained within another element, meaning that we must have a very general CSS rule to hide them, which is not ideal.

**Comment by akfish** [comment] 2017-02-23 12:12
Noted. Will fix in next version.
- [ ] Hiding `<canvas>` element with inline style
- [ ] (Optional) Custom `<canvas>` class name

**Comment by akfish** [comment] 2017-02-27 21:22
Fixed in v3.0.0-alpha.1

Changes made to `<canvas>` element:
* Added `visibility: hidden` as inline style
* Added class name `vibrant-canvas`

**Closed by akfish** 2017-02-27 21:22 UTC
Labels: bug

**Comment by SalGnt** [comment] 2018-07-30 13:41
I still face this problem, even using the latest version.  The problem is that `visibility: hidden` allocate the space of the canvas on the page. I suggest to swap `visibility: hidden` with `display: none` if possible.

**Comment by SalGnt** [comment] 2018-07-30 14:49
I still face this problem, even using the latest version. The problem is that visibility: hidden allocate the space of the canvas on the page. My suggestion is to swap visibility: hidden with display: none if possible.

**Comment by SalGnt** [comment] 2018-07-30 14:50
I still face this problem, even using the latest version. The problem is that with `visibility: hidden` the space of the canvas is allocated on the page. My suggestion is to swap `visibility: hidden` with `display: none`.
