### ISSUE TITLE
Inconsistent values from getPalette()

### ISSUE THREAD

**Issue by daviestar** [akfish/node-vibrant#41] opened 2017-03-15 13:30 UTC
I have a huge list of images that I'm running through `node-vibrant`.  I'm noticing quite often the values of the `getPalette()` object are `null`, instead of an instance of `Swatch`.  

Is this a bug or is there some logic behind this?  It certainly makes it difficult to programmatically associate some colours with an image.

**Comment by cpietsch** [comment] 2017-12-12 16:06
looks like the vibrant palette (normal/light/dark) is returning sometimes null, whereas the muted is always available.

**Comment by AlexThomas90210** [comment] 2018-05-07 03:10
muted is also null sometimes

**Comment by maxcr** [comment] 2018-07-27 12:48
I also get this error. It depends on the image. I'll have to look at akfish's quantizer implementation. From what I've read it isn't a very good method of extracting color and there are other much more suitable algos available.

**Comment by maxcr** [comment] 2018-07-27 13:04
When using getRgb shit was broken about 50% of the time. Using getHex returned valid results always.

**Comment by maxcr** [comment] 2018-08-02 15:07
I eventually just had to use nested loops to see if certain color codes were returning null, and then see if the entire swatch itself was returning null otherwise the promise chain breaks. Probably not very efficient but now my colors load properly in the correct order every time.

**Comment by crutchcorn** [comment] 2018-12-26 17:52
#78 fixes this

**Comment by crutchcorn** [comment] 2019-01-16 16:24
Can someone test against the update `3.1.1` to confirm a fix?

**Comment by Kikobeats** [comment] 2019-06-03 17:47
let me try and pingback if I found problems 👍

**Comment by Kikobeats** [comment] 2019-06-03 18:14
In fact @crutchcorn you can close this, I will comment again if I detect a weird behavior.

Thanks for your effort and time improving the project 🙂

**Comment by crutchcorn** [comment] 2019-06-03 18:19
That's probably for the best, thinking about it more. I have been using the code in a project and have confirmed a fix on my own project. Appreciate keeping an eye out for issues @Kikobeats , feel free to bump thread if issues in future like you mentioned :)

**Closed by crutchcorn** 2019-06-03 18:19 UTC
Labels: awaiting feedback, bug
